Interface:
    Button:
        #text: "[color=#FFBF00][b]Ola[/b][/color] Gamba"
        font_size: '16sp'
        size_hint:None,None
        size:200,100
        #background_color: 0.5,0.5,1,1
        background_normal:'buy.png'
        background_down:'sell.png'
        disabled:True
        background_disabled_normal:'buy.png'
        background_disabled_down:'sell.png'
        pos:root.width/2-100,root.height/2-50
        markup:True